import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header/header";
import { Provider } from "@/components/ui/provider";
import { Box, Grid, GridItem } from "@chakra-ui/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning>
      <body>
        <Provider>
          <Grid height="100vh" templateRows="50px 1fr" bg="white">
            <GridItem>
              <Box bgColor="red" position="fixed" width="100%" top="0">
                <Header />
              </Box>
            </GridItem>
            <GridItem position={"relative"} top={"50px"} rowSpan={2} p={6}>
              <Box>{children}</Box>
            </GridItem>
          </Grid>
        </Provider>
      </body>
    </html>
  );
}
