import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header/header";
import { Provider } from "@/components/ui/provider";
import { Box, Grid, GridItem } from "@chakra-ui/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning>
      <body className="min-h-screen">
        <Provider>
          <Grid
            templateRows="1fr"
            templateColumns="200px 1fr"
            height="100vh"
            bg="white"
            color="gray.900"
          >
            <GridItem>
              <Box height={"100%"}>
                <Header />
              </Box>
            </GridItem>
            <GridItem p={6}>
              <main>{children}</main>
            </GridItem>
          </Grid>
        </Provider>
      </body>
    </html>
  );
}
